name: sport_benefits
version: "1.0.0"
config-version: 2

profile: sport_benefits

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  sport_benefits:
    staging:
      +materialized: view
      +schema: staging

    marts:
      +materialized: table
      +schema: marts

    config:
      +materialized: view
      +schema: config
